### ISSUE TITLE
Search pagination

### ISSUE THREAD

**Issue by pmonson711** [lobsters/lobsters#1211] opened 2023-09-30 14:05 UTC
It appears the pagination links are not setting the `page` query parameter as expected, instead of linking to the expected page it always links back to the current page. It appears to be from the use of the page in the search model.

**Comment by pushcx** [comment] 2023-09-30 16:05
Dupe of #1208 which should've been fixed by #1210.

**Closed by pushcx** 2023-09-30 16:05 UTC
Labels: bug, duplicate
