### ISSUE TITLE
Comments rendered in the wrong order

### ISSUE THREAD

**Issue by lonjil** [lobsters/lobsters#1251] opened 2024-02-11 15:16 UTC
The bottom two comments in the screenshot were in reply to the comment on top, but are drawn below another unrelated comment.

Here are links to the comments in question:
* https://lobste.rs/s/z9rb82/i_don_t_care_about_memory_safety#c_ggutbf
* https://lobste.rs/s/z9rb82/i_don_t_care_about_memory_safety#c_cdvotm
* https://lobste.rs/s/z9rb82/i_don_t_care_about_memory_safety#c_dzqucl

![screenshot-2024-02-11_16:10:51](https://github.com/lobsters/lobsters/assets/885070/6a6b4d10-4c93-4917-8760-1dd1ee4581b5)

**Comment by pushcx** [comment] 2024-02-14 13:58
Unfortunately, this is a dupe of #1236. I’ll post some more info there.

**Closed by pushcx** 2024-02-14 13:58 UTC
Labels: bug, duplicate
