### ISSUE TITLE
Responding to a thread does not properly place your response into the thread

### ISSUE THREAD

**Issue by asthasr** [lobsters/lobsters#428] opened 2017-10-26 12:57 UTC
This is probably related to the recent addition of "thread lines" to the left of threaded comments, but if you reply to the parent of a thread your reply appears immediately below the parent without being added to the "line." Refresh and it's fixed.

**Comment by pushcx** [comment] 2018-01-10 13:21
Closing in favor of #443. It's a dupe of this, but it has convenient screenshots.

**Closed by pushcx** 2018-01-10 13:21 UTC
Labels: bug
