### ISSUE TITLE
Search for "M1" returns no results

### ISSUE THREAD

**Issue by xSetech** [lobsters/lobsters#948] opened 2020-11-26 00:28 UTC
Using the site's search to find stories about Apple's M1 chip returned zero results (see the screenshot):

<img width="721" alt="Screen Shot 2020-11-25 at 4 22 31 PM" src="https://user-images.githubusercontent.com/4540868/100294203-eadea300-2f3a-11eb-93ce-6f25be4b75fa.png">

https://lobste.rs/search?q=M1&what=stories&order=relevance

However, there are definitely stories about the M1, e.g. (from a Google search):
https://lobste.rs/s/veai6u/postgresql_benchmarks_apple_arm_m1
https://lobste.rs/s/ci1xuc

Searches for "Apple M1" succeed, but top results don't include "M1" in the post title:

<img width="804" alt="Screen Shot 2020-11-25 at 4 25 03 PM" src="https://user-images.githubusercontent.com/4540868/100294193-dd291d80-2f3a-11eb-9ed6-e24023656ebe.png">

https://lobste.rs/search?q=Apple+M1&what=stories&order=relevance

Sorting by "Newest" at least gets me a story with "M1" in the title:

<img width="822" alt="Screen Shot 2020-11-25 at 4 26 59 PM" src="https://user-images.githubusercontent.com/4540868/100294293-3abd6a00-2f3b-11eb-9e2d-8ab01408b49d.png">

https://lobste.rs/search?q=Apple+M1&what=stories&order=newest

**Comment by pushcx** [comment] 2020-11-26 00:30
The minimum token size is three characters - this is a dupe of #843

**Closed by pushcx** 2020-11-26 00:30 UTC

**Comment by xSetech** [comment] 2020-11-26 00:33
It would be helpful if the search field displayed a notice about this.
