### ISSUE TITLE
Suggestion: Use GitHub for profile pictures if Gravatar for the user doesn't exist

### ISSUE THREAD

**Issue by RGBCube** [lobsters/lobsters#1228] opened 2023-12-05 08:16 UTC
As per the title, the backend would just serve GitHub's avatar URL for the avatar instead of directly falling back to the default

**Comment by pushcx** [comment] 2023-12-05 15:43
Dupe of #986 and the hassles for this are in #547

**Closed by pushcx** 2023-12-05 15:43 UTC
