### ISSUE TITLE
Enable mailing lists feature seems to be broken

### ISSUE THREAD

**Issue by niko2342** [lobsters/lobsters#1158] opened 2023-02-02 15:00 UTC
I'm trying to enable the mailing list feature by setting "Receive List E-mails" to "Only stories", but it's not possible to submit the form ("Save all Settings"). Tested on Chrome and Firefox.

**Comment by jmiven** [comment] 2023-02-02 19:26
Yes, #1142 and the other referenced issues are caused by the same bug.

**Comment by pushcx** [comment] 2023-02-03 15:09
I'm deploying the fix for this now in 9ec9610a

**Closed by pushcx** 2023-02-03 15:09 UTC
Labels: bug

**Comment by niko2342** [comment] 2023-02-03 16:14
Now, it works as expected. Thank you!
