### ISSUE TITLE
Question marks must be encoded when formatted as quoted-printable in mail headers

### ISSUE THREAD

**Issue by pstef** [lobsters/lobsters#396] opened 2017-09-20 18:55 UTC
https://github.com/lobsters/lobsters/blob/c8d2582fcd9b6074cd6925633c40a7108b8747d1/script/mail_new_activity#L16

Probably needs to be:

```ruby
l.gsub(/=*$/, "").tr(" ", "_").gsub('?', '=3F') << "?=" }.join("\n\t")
```

**Comment by jcs** [comment] 2017-09-26 00:40
Dupe of #328

**Comment by pstef** [comment] 2017-09-26 05:46
I don't see how splitting quoted-printable encoded header across lines is relevant to not encoding the question mark character.

For example "Why use pointers? [go]" ([this story](https://lobste.rs/s/epwmpa)) is a title short enough to not be split (resulting in 43 characters on the whole line), but it still suffers from not encoding the "?" - Thunderbird presents it as "=?UTF-8?Q?Why_Use_Pointers?_[go]?=".

**Comment by pushcx** [comment] 2017-10-06 18:21
Yeah, this is not the same bug.

Whoever can pick this up to fix it, please be sure to include a test. These kinds of fiddly encoding issues are really good at sneaking back into code.

**Comment by evexoio** [comment] 2018-11-27 18:39
I'm taking on this issue, `script/mail_new_activity` uses IO and `sendmail` program to send emails, it's hard to reproduce this issue with `sendmail`, I'm trying to use gmail's smtp, but its not straight forward at all.

Is there any reason why we're not using Rails mailer?

**Comment by alanpost** [comment] 2018-11-27 19:00
On production, lobste.rs uses postfix to send and receive mail:

https://github.com/lobsters/lobsters-ansible/tree/master/roles/postfix

the sendmail binary is the standard interface for sending email on a Unix system.  Compared to an SMTP protocol negotiation, invoking sendmail is materially faster: we send a lot of email.

I do not know if the Rails mailer can be configured to work with sendmail via subprocess/fork/child or whether it only works with SMTP.  We must use the sendmail command-line interface to queue mail, and do so now directly, without requirement to use the Rails mailer.

**Comment by alanpost** [comment] 2018-11-28 11:45
@evexoio,

How do you feel about making a unit test for this change?  @pushcx mentioned it in October 2017:

> Whoever can pick this up to fix it, please be sure to include a test. These kinds of fiddly encoding issues are really good at sneaking back into code.

I'm inclined to agree: a question mark is not the only character we're going to struggle with here, it's rather the first or an early one.  I recognize how difficult it is to test this script as-is, not the least reason being one you've already raised: it invokes /usr/sbin/sendmail.

The String class, however, where this fix is, should be something we can isolate and test.  Are you up for that?

**Comment by pushcx** [comment] 2018-12-05 15:12
@pstef Looks like this may be squared away now. If you see any more examples of this bug, please share them so we can add them to the test suite and improve the fix.

**Comment by pstef** [comment] 2018-12-11 17:55
https://lobste.rs/s/4bx8va shows in my Thunderbird as: AlphaFold @ CASP13: “What just happenedE2=80=9D_[ai]_[science]?=
https://lobste.rs/s/0kqq7a is: =?UTF-8?Q?Why_isn't_it_<style_src=3D"">?_[css]_[historical]?=

**Comment by alanpost** [comment] 2018-12-11 18:08
These did render correctly in IRC, which uses decode_header from the email.header package in Python:

04:25 <mockturtle> AlphaFold @ CASP13: “What just happened?” [ai] [science] (akavel) - https://lobste.rs/s/4bx8va
06:55 <mockturtle> Why isn't it <style src="">? [css] [historical] (flyingfisch) - https://lobste.rs/s/0kqq7a

I'll bring up a Thunderbird environment and see what the difference is.

**Comment by alanpost** [comment] 2018-12-11 18:13
In mutt's index view, one story shows the same rendering issue present in Thunderbird, while the other renders as expected:

AlphaFold @ CASP13: “What just happenedE2=80=9D_[ai]_[science]?=
Why isn't it <style src="">? [css] [historical]

**Comment by evexoio** [comment] 2018-12-14 23:05
@alanpost whats mutt's index view? is it this http://www.mutt.org/?

I'm going to see if I can reproduce on mutt.

**Comment by alanpost** [comment] 2018-12-15 01:05
Mutt's index view is the list of messages in a mailbox.  You have the correct URI.

I think what needs to happen here is formal/library/module support for encoding text (like the subject line) in RFC 2047 compatible format, when the subject line contains non-ASCII characters.

**Comment by evexoio** [comment] 2018-12-15 22:53
<img width="408" alt="1 mutt 2018-12-16 00-35-13" src="https://user-images.githubusercontent.com/12014839/50048030-8f5ad800-00ca-11e9-806e-f09eccda5e99.png">

I couldn't reproduce this bug at the latest master - commit 0b578ac.
can this issue be caused by [prod not being on the latest master.](https://github.com/lobsters/lobsters/issues/621#issuecomment-447521628) it should be right?

**Comment by alanpost** [comment] 2018-12-22 16:54
@pstef, commit 8f46f99 has just been deployed to production.  Please let me know if you get further character encoding errors in mail headers.  Thank you @evexoio for the patch and for your patience in our getting it deployed.

I'll resolve this ticket.  Please write back if you need anything else.

**Closed by alanpost** 2018-12-22 16:55 UTC
Labels: bug, good first issue
