### ISSUE TITLE
Blank Comment Error Message is redundant

### ISSUE THREAD

**Issue by ymeynot45** [lobsters/lobsters#1092] opened 2022-05-31 17:10 UTC
If you have a blank comment box and click either "Post" or "Preview", you end up with a warning box that reads:

_"2 errors prohibited this comment from being saved
There were the problems with the following fields:

Comment can't be blank
Comment cannot be blank."_

It is unnecessary for the message to include the same text with and without the contraction. 
![Lobsters error](https://user-images.githubusercontent.com/2679060/171233180-f9cb587e-5b5d-43cc-8387-e9cb8671a2a2.jpg)

**Comment by pushcx** [comment] 2022-06-01 13:27
Looks like this is a dupe of #978 - which, embarrassingly enough, has an open PR with a fix. Thanks for your report, though. Let me get this fix out.

**Closed by pushcx** 2022-06-01 13:27 UTC
Labels: bug, duplicate, good first issue
