### ISSUE TITLE
Dark theme / night mod for PC

### ISSUE THREAD

**Issue by vladimircicovic** [lobsters/lobsters#637] opened 2019-02-01 00:15 UTC
Could you please add night mode / dark theme for lobster site so ppl who reading could use it. 
Thank you.

**Comment by pushcx** [comment] 2019-02-04 05:21
You can accomplish this with a user style.

This is also a dupe of #404.

**Comment by pushcx** [comment] 2019-03-01 16:29
I saw a [dark mode screenshot](https://twitter.com/lattera/status/1100837450400829440) by @lattera go by on Twitter, he suggested the [Dark Reader](https://darkreader.org/) browser extension. Hope this works out for you.

**Comment by adriangoransson** [comment] 2019-11-22 09:11
Would it be of interest to add a dark mode using the CSS [`prefers-color-scheme` feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)?

Pros:
* No plugin necessary.
* [Pretty good support](https://caniuse.com/#feat=prefers-color-scheme) and **works on mobile**.
* Toggle is on system level and needs no custom UI or per user storage.

I see no explicit downsides except that it requires some more CSS. And the obligatory disagreements on how a dark theme should look.

**Comment by magikid** [comment] 2019-11-22 17:30
I like the `prefers-color-scheme` option but I agree with @pushcx in #404 that this should probably be in a meta thread on lobsters.

**Comment by adriangoransson** [comment] 2019-11-23 09:11
@magikid I agree, but I haven't registered yet. 😀 Would you mind sending me an invite?

**Comment by soc** [comment] 2020-02-11 21:31
I apologize for resurrecting this thread.

I'd be happy to provide a PR implementing a dark mode based on `prefers-color-scheme`, if this doesn't go against https://github.com/lobsters/lobsters/issues/404#issuecomment-333977723.¹

The good thing about `prefers-color-scheme` is that the concern raised in the comment regarding

> A single toggle to a dark theme seems OKish if someone can suggest a good place in the UI for it

is not an issue, as `prefers-color-scheme` does not require any toggle or UI change to work.

---

¹ There are two ways I'm able to read @pushcx comment, either as "I'll consider implementing this if there is overwhelming demand" or as "I'll accept an implementation if there is overwhelming demand". If it's the former, I'm happy to provide a PR.

**Comment by pushcx** [comment] 2020-02-12 04:24
Sounds like a great approach that doesn't make the site any more complicated. I'd merge a PR for it.

**Comment by soc** [comment] 2020-02-12 11:10
@pushcx Cool, thanks!

**Comment by soc** [comment] 2020-02-12 22:44
Is there a way to get a Lobste.rs instance running without the database setup mentioned in the README?

**Comment by pushcx** [comment] 2020-02-13 04:59
No, without the database it would have nothing to present. If you don't want to do the setup hassle, I'd say just Save pages in your browser as "web page, complete" and you'll have the css files in front of you to tweak and reload in the browser without any gem/rails/db hassles. When you're done, copy it into the repo and submit a PR.

**Comment by soc** [comment] 2020-02-13 13:21
Ah, thanks! I came up with a similar way: Editing the CSS file in the IDE and just pasting it into the style editor in the browser tools.

I factored out all the relevant CSS colors to variables already – which will make it much easier to adjust things (also with users' own userstyles that some may prefer).

This brings me to the question: Are we supporting IE11? (then I'll also add the required [polyfill](https://github.com/jhildenbiddle/css-vars-ponyfill))

(I tried switching to ActiveRecord's `sqlite` adapter, instead of the `mysql` one, but that didn't work ...)

**Comment by soc** [comment] 2020-02-13 21:46
Submitted a PR in https://github.com/lobsters/lobsters/pull/823.

**Comment by pushcx** [comment] 2020-02-14 03:33
We don't serve js to logged-out users and MS still hasn't apologized for 90s IE, so, no.

**Comment by soc** [comment] 2020-02-14 12:23
Great! :-)

**Comment by pushcx** [comment] 2020-07-14 01:23
Done by @soc in #823.

**Comment by nikhiljha** [comment] 2020-07-14 01:57
![image](https://user-images.githubusercontent.com/2773700/87371604-919d4680-c53a-11ea-8441-310fc93746f2.png)

I just opened lobsters on my phone and the low-contrast is kinda killing my eyes; can we revert and bikeshed colors some more (or at least make sure we conform to the WCAG guidelines)?

**Comment by pushcx** [comment] 2020-07-14 02:41
When you mention WCAG Guidelines, are you thinking of the [color contrast guidelines](http://web-accessibility.carnegiemuseums.org/design/color/) or something else?

**Comment by nikhiljha** [comment] 2020-07-14 03:09
Yes, the color contrast guidelines. Thanks for the clarification.

**Comment by pushcx** [comment] 2020-07-14 03:22
There's no way I'm plugging in every single possible pair of colors into a rando tool one at a time for those vague guidelines, but it's moot as I reverted in 65b0b34. Browser support is insufficient for development. We can revisit when that's there.

**Comment by nikhiljha** [comment] 2020-07-14 07:26
As for testing colors, there are well-known dark theme colors we can just copy. I think Apple's are pretty good, but there are others.

---

As for browser support, this is pretty much complete. p-c-s works on:

- All Apple Devices
- Modern versions of Android (10+)
- Windows (Firefox, Chrome, Most Chrome Derivatives)
- Linux (Firefox)

In all the above cases, dark theme is configured in the OS settings, **not the browser settings**, which seemed to be confusing people in IRC. The only major missing player is Chrome on Linux.

**Comment by soc** [comment] 2020-07-14 07:48
Re

> Firefox support is half-baked. There's no user or devtool UI to toggle between
states, inspecting an element always shows the style for ::selection instead of
the element, and it lists the name of a color variable with no way to see the
value of the variable or where it is set. Punting until it's debuggable.

I also realized that I lost the ability to switch between light mode and dark mode, because my Gtk theme is now correctly marked as a dark theme, which makes Firefox pick the dark CSS theme by default and ... Firefox lacks the ability to switch back to light mode. Yikes.

**Comment by pushcx** [comment] 2020-07-14 14:15
Yeah. I'm not opening my wm config, restarting my browser, or waiting twelve hours to toggle back and forth between light and dark. Let alone dealing with devtools showing the wrong selector and having no view into variables.

**Comment by adriangoransson** [comment] 2020-07-14 14:59
Strange that Firefox doesn't have the option to switch manually, even in the "developer edition". There's always [extensions](https://addons.mozilla.org/en-US/firefox/addon/dark-mode-website-switcher) though.

@pushcx As for debugging, am I missing something? I can inspect variables just fine by hovering over them. The root namespace is inherited and its definition is shown last. Although one annoying issue with the extension is that I need to reselect the dom element to update the ruleset.

Image below of what I mean. Though it is not from lobste.rs.
<img width="679" alt="Screen Shot 2020-07-14 at 16 49 54" src="https://user-images.githubusercontent.com/4947727/87440426-4181bb00-c5f2-11ea-8cf8-1a97223c476f.png">

**Comment by soc** [comment] 2020-07-15 10:31
> There's always extensions though.

@adriangoransson that's the one I'm using, and it doesn't work for the reasons mentioned above.

**Comment by kconner** [comment] 2021-09-13 18:43
If I've understood all this, the task remaining is to choose a nice set of colors for dark mode that pass WCAG color contrast guidelines, then prepare a PR with an un-revert of 65b0b34 plus the color changes. Is that accurate?

If so, I'd be happy to take that on this week. I'm on macOS and iOS and could solicit spot checks from other platforms.

**Comment by pushcx** [comment] 2021-09-13 19:32
Yeah. The browser dev tooling has caught up and now this is trivial to test and debug.

**Comment by kconner** [comment] 2021-09-13 23:21
My todo list:

- [x] Revert the revert of dark mode work
- [x] Honor the rename of "downvote" to "flag" within CSS
- [ ] Capture in variables all colors from properties not already using variables. Many seem to have been added since last summer.
- [ ] Capture in variables all colors in mobile.css. Mobile dark mode was not implemented before, unless I lost something in the revert.
- [ ] Look for ways to derive distinct colors from a small main palette, for instance, mixing many intensities or opacities with a single defined red. This would yield clearer relationships between colors and more obvious choices when styling. Today there are at least 50 distinct explicit colors.
- [ ] Check WCAG color contrast and fix as needed.

**Closed** 2021-09-29 17:43 UTC
Labels: duplicate, featurereq
